ci.nix
src/pinned-pkgs.nix
src/pkgs/default.nix
src/pkgs/nix-directory.nix
src/pkgs/nix-installer-sha256.nix

Hey, I just open a new PR for cachix support as we started to discuss in https://github.com/t184256/nix-on-droid-bootstrap/pull/13.
I tested it on my computer with following steps:
1. Build and push store paths with `nix-build ci.nix | cachix push gerschtli`
2. Remove generated gcroots:
```bash
rm result*
nix-collect-garbage
```
3. Build and fetch store paths again with `nix-build ci.nix` (cachix binary cache has to be registered locally already):
```
copying path '/nix/store/vl48fgr1v9j2lsncxlwh3ifzh2h9w70r-source' from 'https://cache.nixos.org'...
building '/nix/store/5bibwf4y9lz8c952q7q18rv4nyh35jhx-nix-installer-sha256.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup …
```

Try to add cachix support

---

modules/build/activation.nix
modules/environment/login/login-inner.nix
modules/environment/session-init.nix
modules/module-list.nix
pkgs/nix-directory.nix

Hey,
I added `environment.sessionVariables` option and fixed https://github.com/t184256/nix-on-droid-bootstrap/issues/35.

Manage environment variables

---

modules/build/activation.nix
modules/home-manager.nix

When enabling `home-manager.useUserPackages`, there is a conflict of duplicate package installations. Through increasing priority value this can be avoided.

Increase priority value to avoid conflict

---

modules/home-manager.nix

Adds new option to be able to set `HOME_MANAGER_BACKUP_EXT` (see `-b` flag for home-manager) via nix-on-droid config.

home-manager: Add backupFileExtension option

---

modules/environment/login/login-inner.nix

Source session-init on initial build which closure is added in `nix-directory`.
Can you test it? I don't want to wipe my data again.. :D

login-inner: source session-init on initial build

---

modules/default.nix
modules/module-list.nix
modules/nixpkgs.nix

Now it is possible to define config and overlays in nix-on-droid config which is a necessary step for https://github.com/t184256/nix-on-droid-bootstrap/issues/23

Add nixpkgs.config and overlays option

---

nix-on-droid/nix-on-droid.sh

Pass -I argument to nix-build.
Closes https://github.com/t184256/nix-on-droid-bootstrap/issues/40

nix-on-droid: add -I argument

---

modules/environment/login/login-inner.nix
modules/environment/session-init.nix
pkgs/nix-directory.nix

With this change, everything to setup the session is separated into the session-init.sh. This has the advantage that when logged in via ssh, you only need to source one file, instead of up to 3.

Add source nix.sh and hm-session-vars.sh in session-init.sh

---

modules/environment/login/login-inner.nix
modules/user.nix
pkgs/default.nix

This change allows to change the login shell through providing the full path to the binary.
In case the binary is not present or executable, bash will be run instead.
Through the failsafe shell it is possible to override the passwd and change the shell manually

Add support for different login shells

---

README.md
default.nix
modules/build/initial-build.nix
modules/environment/login/nix-on-droid.nix.default
modules/home-manager.nix
modules/version.nix

This PR introduces changes needed for the 20.03 release of home-manager. On 19.09 releases of home-manager this won't work.
Furthermore I added the useGlobalPkgs option recently introduced to home-manager.

home-manager 20.03 upgrade

---

flake.nix

With this change, the overlays are used when using flakes.
related to https://github.com/t184256/nix-on-droid/issues/94#issuecomment-850849580

flake.nix: fix overlays

---

overlays/lib/nixpkgs.nix

Any idea what to do with this:
https://github.com/t184256/nix-on-droid/blob/78d349eecc2382b65c6d93f4ef15d5588db169c6/modules/nixpkgs.nix#L169
Does non-flake use `system`?
EDIT: maybe `{ system ? builtins.currentSystem }:`

overlays/lib/nixpkgs.nix: use system

---

modules/build/activation.nix

Set profile with the store path instead of the path of the "result" link.
Solve #111

activation.nix: fix for "activation from build result"

---

modules/default.nix

Options are useful for documentation purposes and can be used by things like [nix-option](https://github.com/lucasew/nix-option) and automatic documentation generation systems.

Expose options

---

modules/build/activation.nix

Solve #111 
Fix the activation script by dropping the line
```bash
cd $HOME
```
in `activation.nix`

activation.nix: fix for "activation from build result" (revised)

---

flake.nix
modules/default.nix
modules/home-manager.nix

This allows `pkgs` and `home-manager` to be easily overridden for custom configs. We also fix the `overlay` output so that the output attribute set matches the standard schema (`nix flake check`).

flake.nix: Clean up, allow overriding pkgs

---

modules/environment/login/login-inner.nix
nix-on-droid/nix-on-droid.sh
tests/on-device/.run.sh
tests/on-device/config-default.bats
tests/on-device/config-flake-h-m.bats
tests/on-device/config-flake-h-m.cfg.nix
tests/on-device/config-flake-h-m.flake.nix
tests/on-device/config-flake.bats
tests/on-device/config-flake.nix
tests/on-device/config-h-m.bats
tests/on-device/config-h-m.nix
tests/on-device/gnumake.bats
tests/on-device/hello.bats
tests/on-device/lib.bash

I've decided to quick-and-dirty automate a few things I often check manually on PRs and releases inside a disposable installation.
@Gerschtli thoughts? Other high-profile scenarios I'm missing?

WIP: On-device tests

---

.github/workflows/fakedroid-odt.yml

Secrets are not available when triggered by a PR. Therefore, `CACHIX_SIGNING_KEY` is not defined and cachix will always fail.

ci: do not attempt to push to cachix on PR builds

---

modules/build/activation.nix

The explanation/description of the `VERBOSE*` env vars for the activation scripts was missing.

activation: add VERBOSE env var in option description

---

README.md
flake.nix
modules/default.nix
nix-on-droid/default.nix
nix-on-droid/nix-on-droid.sh
pkgs/default.nix
tests/fakedroid.sh
tests/on-device/.run.sh
tests/on-device/config-default.bats
tests/on-device/config-flake-h-m.bats
tests/on-device/config-flake-h-m.flake.nix
tests/on-device/config-flake.bats
tests/on-device/config-flake.nix
tests/on-device/config-h-m.bats
tests/on-device/gnumake.bats
tests/on-device/lib.bash

This is my first draft of a more native integration of flakes support including
* conventions for `nixOnDroidConfigurations` and `nixOnDroidModules` flake outputs
* support for flakes in `nix-on-droid` tool
* support for `extraModules` and `extraSpecialArgs` similar to `home-manager` and `NixOS`
Any feedback on the API and documentation would be appreciated. The actual code changes are not tested yet, but the earlier I get feedback on my main ideas the better :)
This one supersedes https://github.com/t184256/nix-on-droid/pull/145, incorporating all its changes. The reason to not wait for its merge is to only change the `lib` output of the `nix-on-droid` once and I wanted these fields like `extraModules` and `extraSpecialArgs` in there :)
Ping @zhaofengli @ShamrockLee @bbigras as you were …

More native flake support

---

modules/module-list.nix
modules/upgrade.nix

Fixes: #162
I plan for this to be the last MR going into the release, I haven't find other issues during upgrade testing.
Activation-time quick fix was chosen over login-time quick fix because I can imagine a hot loop around login, but activation is slow in comparison.

modules/build/activation.nix: fix missing /dev/shm on upgrade

---

modules/environment/nix.nix

Per #166, complete compatibility with NixOS is a non-goal, and nix-on-droid options won't be renamed to match.
But it won't hurt to add compatibility where possible, and it's much simpler to do so here than to try to make the rest of the world change.

module/nix: Add backward compat with nixos for binary caches

---

nix-on-droid/default.nix
nix-on-droid/nix-on-droid.sh

This pull request updates the nix-on-droid derivation so it doesn't force `nix_2_4` when the `nix` package is newer than `2.4pre`. This allows people using more recent channels like nixpkgs-unstable to evaluate their flake configurations using the latest version of nix, while ensuring that those using older nix versions can still evaluate flakes (I believe 2.4 is the first version that supported flakes?).
I have tested this change using the following flake:
```nix
{
description = "CHANGEME";
inputs = {
nixpkgs.url = "nixpkgs/release-21.11";
utils.url = "github:numtide/flake-utils";
nix-on-droid = {
url = "github:mtoohey31/nix-on-droid/dont-force-nix_2_4";
inputs = {
flake-utils.follows = "utils";
nixpkgs.follows = "nixpkgs";
};
};
};
outputs = { self, nixpkgs, nix-on-droid, utils }: …
```

fix: don't force the use of nix_2_4 for flakes when nix is new enough

---

modules/environment/login/login-inner.nix
pkgs/bootstrap.nix
pkgs/nix-directory.nix

This PR bumps the bootstrap Nix version to 2.11.0. This brings in a newer version of glibc which fixes issues with devices with BTI functionality. Since newer Nix bootstrap tarballs no longer include coreutils, let's also remove our dependency on it.
Tested on the Exynos variant of Galaxy S22 (SM-S901B). Fixes #199.

Bump bootstrap nix to 2.11.0

---

CHANGELOG.md
modules/environment/login/login.nix

This applies the workaround in https://github.com/SDRausty/TermuxArch/issues/175 when `/proc/uptime` is not readable. Fixes #77.

login: Add fake /proc/uptime workaround for ps

---

modules/environment/nix.nix

Fixes https://github.com/t184256/nix-on-droid/issues/190

environment.nix: fix NIX_PATH environment variable

---

modules/home-manager.nix

Prepend of /. produces directory not found error when building on a non nix-on-droid environment. The etc module works also with just a string.

home-manager: fix directory not found error

---

.github/workflows/lints.yml
flake.lock
flake.nix
modules/environment/nix.nix
modules/nixpkgs/config.nix
modules/nixpkgs/options.nix
modules/time.nix
overlays/typespeed.nix

I build a nice little tool to easily setup multiple formatters (we currently use nixpkgs-fmt and statix, this adds [deadnix](https://github.com/astro/deadnix)). The benefit is that running `nix fmt` fixes all issues found by all tools and `nix flake check` checks for all tools.
This is very opinionated so feel free to close it, if you don't like it :)
Requires https://github.com/t184256/nix-on-droid/pull/204.

Add nix-formatter-pack

---

CHANGELOG.md
README.md
flake.nix
modules/default.nix
modules/environment/login/login-inner.nix
modules/environment/session-init.nix
modules/module-list.nix
nix-on-droid/nix-on-droid.sh
pkgs/default.nix
templates/advanced/flake.nix
templates/home-manager/flake.nix
templates/minimal/flake.nix
tests/on-device/config-flake-default.nix
tests/on-device/config-flake-h-m.flake.nix
tests/on-device/config-flake.bats
tests/on-device/config-flake.nix

This PR includes some things:
- fix usage of `extraSpecialArgs` (we did not set the values of this argument as special arg but as `_module.args` which disallows usage of these values in `imports` in config modules)
- remove parameters/simplify usage of `lib.nixOnDroidConfiguration` (inspired by https://github.com/nix-community/home-manager/pull/3037)
- add option for text on shell startup to allow changing or removing it
- add support for `default` config in `flake`, this is an easy convenience helper for people only using one device
- some improvements for fakedroid environment testing
If you want me to split some commits into separate PRs, I can do that, but this may result in some merge conflicts that I tried to avoid with this big PR :)
Sorry for the high load of PRs lately, got quite …

Improvements for flake usage

---

.github/workflows/docs.yml

Copy-paste error, sorry.
BTW: You may need to enable gh pages in the repo settings. I am not 100% sure.

ci: fix incorrect path to docs directory

---

modules/terminal.nix

**Problem:**
Currently, if one wants to use a font, whose path contains spaces, for instance a nerdfont:
```nix
{
terminal.font =
let
firacode = pkgs.nerdfonts.override {
fonts = [ "FiraCode" ];
};
fontPath = "share/fonts/truetype/NerdFonts/Fira Code Regular Nerd Font Complete Mono.ttf";
in
"${firacode}/${fontPath}";
}
```
`nix-on-droid` would fail to create a correct symlink because the references to `${fontTarget}` aren't quoted which leads to `ln` treating the space-separated parts of the font name as different arguments.
Quoting `man ln`/`LN(1)`:
```
Given more than two arguments, ln makes links in target_dir to all the named
source files.  The links made will have the same name as the files being linked
to.
```
which isn't the wanted behaviour here.
**Solution:**
Quote all unquoted …

fix(terminal.nix): quote font paths

---

CHANGELOG.md
modules/environment/path.nix

Allow to install extra outputs.
This is useful to e. g. install `info` documentation automatically.
This option was modelled after NixOS's option [environment.extraOutputsToInstall](https://search.nixos.org/options?channel=unstable&show=environment.extraOutputsToInstall&from=0&size=50&sort=relevance&type=packages&query=environment.extraOutputsToInstall).

modules/environment/path: add environment.extraOutputsToInstall option

---

.github/workflows/cachix.yml
.github/workflows/docs.yml
.github/workflows/fakedroid-odt.yml
.github/workflows/lints.yml

Our actions are using outdated versions. This would have become more obvious if we would run our CI regularly. I added a weekly scheduler.

Update GitHub actions and run weekly

---

AUTHORS
CHANGELOG.md
modules/environment/networking.nix
tests/on-device/config-flake-hosts-localhost.cfg.nix
tests/on-device/config-flake-hosts.bats
tests/on-device/config-flake-hosts.cfg.nix

Tested on my phone with yggdrasil - works fine :)

Add networking options.

---

modules/build/config.nix

String was deprecated in nixpkgs.
It fails to build with unstable nixpkgs now: https://github.com/NixOS/nixpkgs/pull/247848

build: use str instead of string

---

flake.lock
flake.nix

Gitlab nmd has been archived, use sourcehut:~rycee/nmd instead. Notably, the result has a reworked auto dark/light theme.

flake.lock, flake.nix: update nmd, use sourcehut:~rycee/nmd

---

modules/terminal.nix
tests/on-device/config-term-colors.bats
tests/on-device/config-term-colors.nix
tests/on-device/lib.bash

This implements basic support for termux's colorschemes (`~/.termux/colors.properties`) through the new option `terminal.colors`. It takes an attribute set of strings and naively converts that to the key-value format termux expects, e.g. 
```nix
terminal.colors = rec {
background = color0;
foreground = color15;
cursor = color15;
color0 = "#000000";
color15 = "#FFFFFF";
};
```
would become 
```
background=#000000
color0=#000000
color15=#FFFFFF
cursor=#FFFFFF
foreground=#FFFFFF
```
I wasn't sure whether to use `attrsOf` or `lazyAttrsOf`, so I chose the latter as a guess.
I've mostly just copied over the implementation from what fonts do, I hope that's correct.
There are a couple issues with this as it stands:
1. Colors aren't strictly checked, you can input any string.
2. Attributes aren't …

Implement termux colorschemes

---

.github/workflows/emulator.yml
CHANGELOG.md
modules/environment/android-integration.nix
modules/module-list.nix
pkgs/android-integration/termux-am.nix
pkgs/android-integration/termux-tools.nix
pkgs/android-integration/termux-tools.patch
tests/emulator/android_integration.py
tests/emulator/bootstrap_channels.py
tests/emulator/bootstrap_flakes.py
tests/on-device/config-android-integration.bats
tests/on-device/config-android-integration.nix

~~(sorry, there will be a CI failure in test_channels_uiautomator because a warning pushes success message off-screen. will deal with it tomorrow)~~ fixed

modules/android-integration: add am command and many termux-tools ones

---

AUTHORS
modules/environment/login/login.nix
tests/emulator/test_channels_shell.py

`/bin` and `/etc` are symlinks to `/system/bin` and `/system/etc`, by default proot will dereference and override them with new contents.
After this change, `/system/bin` and `/system/etc` are kept untouched, so commands like `/system/bin/ping` can be run directly.

login: Do not dereference proot binds `/bin` and `/etc`

---

modules/environment/login/login-inner.nix
tests/emulator/poke_around.py

Setting `user.shell = pkgs.fish` or similar is a common footgun that completely breaks the nix-on-droid. See #284.
This PR try to address the problem by checking that if the shell is a directory and falling back to bash in that case. This fix the common cause that many people hit that issue, but a general fix for that issue should probably include a way to switch generations without using the terminal, since setting the `user.shell` wrongly isn't probably the only way to break nix-on-droid.

Check if the selected shell is a directory

---

.github/workflows/emulator.yml

The `DeterminateSystems/magic-nix-cache-action` action has been [deprecated](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) and no longer works. This PR replaces it with the `nix-community/cache-nix-action` action, which is actively maintained. It also replaces the `DeterminateSystems/nix-installer-action` action with the `nixbuild/nix-quick-install-action` action, which is required for the cache action to work. The cache has been configured to restore based on the runner's OS and architecture, so it should work on any runner.

Replace magic-nix-cache-action

---

nix-on-droid/nix-on-droid.sh

With this addition, we would simplify the development cycle of stylix modules when using flakes:
`nix-on-droid switch --flake . --override-input stylix git+file:/home/user/path/to/stylix`
since we wouldn't need to to do a `nix flake lock --update-input stylix` for every edit to the local stylix input.

nix-on-droid: passthrough --override-input arg

---

.github/workflows/emulator.yml

This reverts commit af711651ca02d6918a479942be5d87fde2c352ee.

Revert "Allow unfree packages when building droidctl"

---

modules/default.nix
tests/on-device/config-class.bats

This is useful for getting better error messages when mixing modules; a module designed for nixos configs sets `_class = "nixos";` and then when you try to use it from a nix-on-droid config it shows an error.
See: https://nixos.org/manual/nixpkgs/unstable/#module-system-lib-evalModules-param-class

Pass class="nixOnDroid"; to evalModules
